backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
  
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "images", widget: "image"}
      - { label: "Description", name: "description", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["poem", "my poem", "translate", "shitpost", "writing", "my fav"]
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Poetry", "Book", "Life", "My Atleti", "Thought", "Random"]
